---
title: "Codebase"
output: pdf_document
date: "2022-11-04"
---
## Update

## Try to edit the content

### Original model
```{r}
test <- read.csv("AcctestNoYNew.csv")
train <- read.csv("Acctrain.csv")
cityPop = read.csv("cityPop.csv")
largeCities = cityPop[cityPop$population>=500000,"city"]
colnames(cityPop)[1] = "population"
```

```{r}
# sapply(as.data.frame(is.na(train)), sum)
# train$Temperature.F.[is.na(train$Temperature.F.)] <- mean(train$Temperature.F.[!is.na(train$Temperature.F.)])
# 
# train$Wind_Chill.F.[is.na(train$Wind_Chill.F.)] <- mean(train$Wind_Chill.F.[!is.na(train$Wind_Chill.F.)])
# 
# train$Pressure.in.[is.na(train$Pressure.in.)] <- mean(train$Pressure.in.[!is.na(train$Pressure.in.)])
# 
# train$Visibility.mi.[is.na(train$Visibility.mi.)] <- mean(train$Visibility.mi.[!is.na(train$Visibility.mi.)])
# 
# train$Wind_Speed.mph.[is.na(train$Wind_Speed.mph.)] <- mean(train$Wind_Speed.mph.[!is.na(train$Wind_Speed.mph.)])
# 
# train$City[is.na(train$City)] =
#   mode(train$City[!is.na(train$City)])

# model1 <- glm(as.factor(Severity)~Start_Lat+Start_Lng+End_Lat+End_Lng+Temperature.F.+Wind_Chill.F.+Pressure.in.+Visibility.mi.+Wind_Speed.mph., family = binomial(), data = train)

# sapply(as.data.frame(is.na(test)), sum)
# test$Temperature.F.[is.na(test$Temperature.F.)] <- mean(test$Temperature.F.[!is.na(test$Temperature.F.)])
# 
# test$Wind_Chill.F.[is.na(test$Wind_Chill.F.)] <- mean(test$Wind_Chill.F.[!is.na(test$Wind_Chill.F.)])
# 
# test$Pressure.in.[is.na(test$Pressure.in.)] <- mean(test$Pressure.in.[!is.na(test$Pressure.in.)])
# 
# test$Visibility.mi.[is.na(test$Visibility.mi.)] <- mean(test$Visibility.mi.[!is.na(test$Visibility.mi.)])
# 
# test$Wind_Speed.mph.[is.na(test$Wind_Speed.mph.)] <- mean(test$Wind_Speed.mph.[!is.na(test$Wind_Speed.mph.)])
# 
# test$City[is.na(test$City)] =
#   mode(test$City[!is.na(test$City)])
# testPred <- predict(model1, test, type="response")

# pred <- ifelse(testPred >= 0.5, "SEVERE", "MILD")
#sample <- cbind(Sample[1], pred)
#names(sample) <- c("Ob", "SEVERITY")
#write.csv(sample, "sample.csv", row.names = FALSE)
```

```{r}
# summary(model1)
```

```{r}
# trainPred <- predict(model1, type="response")
# predTrain <- ifelse(trainPred >= 0.5, "SEVERE", "MILD")
# table(train$Severity, predTrain)
# mean(train$Severity == predTrain)
```


## New model

### Add the duration predictor
```{r}
library(stringr)
library(lubridate)
train$duration<-as.numeric(as.POSIXct(train$End_Time,
                                      format = "%Y-%m-%dT%H:%M"))-
  as.numeric(as.POSIXct(train$Start_Time, 
                        format = "%Y-%m-%dT%H:%M"))

test$duration<-as.numeric(as.POSIXct(test$End_Time,
                                      format = "%Y-%m-%dT%H:%M"))-
  as.numeric(as.POSIXct(test$Start_Time, 
                        format = "%Y-%m-%dT%H:%M"))

train$time = ymd_hms(train$Start_Time)
test$time = ymd_hms(test$Start_Time)

train$hour=hour(train$time)
test$hour=hour(test$time)

train$month=month(train$time)
test$month=month(test$time)

train$year = year(train$time)
test$year = year(test$time)

train$isRushHour = train$hour %in% c(7,8,17,18)
test$isRushHour = test$hour %in% c(7,8,17,18)

train$Description = tolower(train$Description)
test$Description = tolower(test$Description)

train$DescriptionLen = nchar(train$Description)
test$DescriptionLen = nchar(test$Description)


train$road_closed<-str_detect(train$Description, "road closed")
test$road_closed<-str_detect(test$Description, "road closed")

# train$exit<-str_detect(train$Description, "exit")
# test$exit<-str_detect(test$Description, "exit")

# train$ramp_str<-str_detect(train$Description, "ramp")
# test$ramp_str<-str_detect(test$Description, "ramp")

train$slow<-str_detect(train$Description, "slow")
test$slow<-str_detect(test$Description, "slow")

train$caution<-str_detect(train$Description, "caution")
test$caution<-str_detect(test$Description, "caution")

train$interstate<-str_detect(train$Description, "i-")
test$interstate<-str_detect(test$Description, "i-")

wy = c("fwy", "pkwy")
train$wy<-str_detect(train$Description, wy)
test$wy<-str_detect(test$Description, wy)

high.risk.states = c("CA","TX","IL","FL","CO")
train$isHighRiskState<-train$State %in%
  high.risk.states
test$isHighRiskState<-test$State %in%
  high.risk.states
# ggplot(aes(x = as.factor(Severity), 
#            y = duration), data = accTrain) + 
#   geom_boxplot()

```

### Add isWeekend predictor

```{r}
# train$weekday = weekdays(accTrain$Start_Time)
train$isWeekend = weekdays(as.POSIXct(train$Start_Time)) %in% c("Saturday",
                                                         "Sunday")
train$isWeekend = ifelse(train$isWeekend==TRUE, 1, 0)

test$isWeekend = weekdays(as.POSIXct(test$Start_Time)) %in% c("Saturday",
                                                         "Sunday")
test$isWeekend = ifelse(test$isWeekend==TRUE, 1, 0)
```


### Add isLargeCity

```{r}
train$isLargeCity = train$City %in% largeCities
test$isLargeCity = test$City %in% largeCities
```

```{r}
train$Bump = ifelse(train$Bump == TRUE, 1, 0)
train$Give_Way = ifelse(train$Give_Way == TRUE, 1, 0)
train$No_Exit = ifelse(train$No_Exit == TRUE, 1, 0)
train$Roundabout = ifelse(train$Roundabout == TRUE, 1, 0)
train$Traffic_Calming = ifelse(train$Traffic_Calming == TRUE, 1, 0)
train$Turning_Loop = ifelse(train$Turning_Loop==TRUE, 1, 0)

test$Bump = ifelse(test$Bump == TRUE, 1, 0)
test$Give_Way = ifelse(test$Give_Way == TRUE, 1, 0)
test$No_Exit = ifelse(test$No_Exit == TRUE, 1, 0)
test$Roundabout = ifelse(test$Roundabout == TRUE, 1, 0)
test$Traffic_Calming = ifelse(test$Traffic_Calming == TRUE, 1, 0)
test$Turning_Loop = ifelse(test$Turning_Loop==TRUE, 1, 0)
```


```{r}
# sapply(as.data.frame(is.na(train)), sum)
train$Temperature.F.[is.na(train$Temperature.F.)] <- median(train$Temperature.F.[!is.na(train$Temperature.F.)])

train$Wind_Chill.F.[is.na(train$Wind_Chill.F.)] <- median(train$Wind_Chill.F.[!is.na(train$Wind_Chill.F.)])

train$Pressure.in.[is.na(train$Pressure.in.)] <- median(train$Pressure.in.[!is.na(train$Pressure.in.)])

train$Visibility.mi.[is.na(train$Visibility.mi.)] <- median(train$Visibility.mi.[!is.na(train$Visibility.mi.)])

train$Wind_Speed.mph.[is.na(train$Wind_Speed.mph.)] <- median(train$Wind_Speed.mph.[!is.na(train$Wind_Speed.mph.)])

# library(class)
# 
# train.test.X = train[train.test.index, c(20, 21, 23,24, 26,29,31,33,35,38,40,45,46)]
# train.train.X = train[-train.test.index, c(20, 21, 23,24, 26,29,31,33,35,38,40,45,46)]
# train.test.Y = train[train.test.index, 1]
# train.train.Y = train[-train.test.index, 1]
# 
# train.train = cbind(train.train.Y, train.train.X)
# 
# knn.model<-knn(train.train.X,train.test.X,train.train.Y,k=9)
# #
# table(knn.model,train.test.Y)
# #
# mean(knn.model==train.test.Y)
# 
# train.train = train[-train.test.index, c(20, 21, 23,24, 26,45,46)]
# train.train$Severity = train[-train.test.index, 1]
# 
# train.test = train[train.test.index, c(20, 21, 23,24, 26,45,46)]
# train.test$Severity = train[train.test.index, 1]

# model1 <- glm(as.factor(Severity)~Temperature.F.+
#                 Wind_Chill.F.+
#                 Pressure.in.+
#                 Visibility.mi.+
#                 Wind_Speed.mph.+
#                 duration+
#                 isWeekend+Bump+
#                 Give_Way+
#                 No_Exit+
#                 Roundabout+
#                 Traffic_Calming+Turning_Loop, family = binomial(), data = train)

# sapply(as.data.frame(is.na(test)), sum)
test$Temperature.F.[is.na(test$Temperature.F.)] <- median(test$Temperature.F.[!is.na(test$Temperature.F.)])

test$Wind_Chill.F.[is.na(test$Wind_Chill.F.)] <- median(test$Wind_Chill.F.[!is.na(test$Wind_Chill.F.)])

test$Pressure.in.[is.na(test$Pressure.in.)] <- median(test$Pressure.in.[!is.na(test$Pressure.in.)])

test$Visibility.mi.[is.na(test$Visibility.mi.)] <- median(test$Visibility.mi.[!is.na(test$Visibility.mi.)])

test$Wind_Speed.mph.[is.na(test$Wind_Speed.mph.)] <- median(test$Wind_Speed.mph.[!is.na(test$Wind_Speed.mph.)])

# testPred <- predict(model1, test, type="response")

# pred <- ifelse(testPred >= 0.5, "SEVERE", "MILD")
# sample = data.frame(Ob=1:15000, SEVERITY=pred)
# write.csv(sample, "sample.csv", row.names = FALSE)
```

## Text Analysis
```{r}
# mild.description = train[train$Severity=="MILD",
#                          "Description"]
# sever.description =
#   train[train$Severity=="SEVERE",
#         "Description"]
# write.csv(mild.description, "mild_desc.csv", row.names = FALSE)
# write.csv(sever.description, "severe_desc.csv", row.names = FALSE)

```
 

## Tree Model

### Training as testing
```{r}
set.seed(1128)
train.test.index<-sample(1:nrow(train), 0.3*nrow(train), replace = F)
train.train.data = train[-train.test.index,]
train.test.data = train[train.test.index,]
```

### Full training data
```{r}
library(tree)
tree.model = tree(as.factor(Severity) ~ 
                        road_closed+
                        duration+
                        isWeekend+
                        caution+
                        Distance.mi.+
                        slow+
                        DescriptionLen+
                        isHighRiskState+
                        interstate+
                          hour+
                          month+
                          year+
                          County+
                          Visibility.mi.+
                          isLargeCity,
                  train.train.data)
summary(tree.model)

# pred <- ifelse(testPred >= 0.5, "SEVERE", "MILD")
# sample = data.frame(Ob=1:15000, SEVERITY=pred)
# write.csv(sample, "sample.csv", row.names = FALSE)

train.test.pred = predict(tree.model, newdata = train.test.data,
                         type = "class")
table(train.test.pred, train.test.data$Severity)
tree.mis.rate=mean(train.test.pred!=train.test.data$Severity)
tree.mis.rate

misclassified.index = which(train.test.pred=="MILD" & train.test.data$Severity=="SEVERE")
misclass.data = train.test.data[misclassified.index,]
write.csv(misclass.data, 
          "misclassified_data.csv", row.names = FALSE)

misclass.data%>%
  group_by(State)%>%
  summarise(proportion = n()/650)%>%
  arrange(desc(proportion))

write.csv(misclass.data$Description, 
          "mis_desc.csv", row.names = FALSE)

```

```{r}
testPred = predict(tree.model, newdata = test,
                         type = "class")
# pred <- ifelse(testPred >= 0.5, "SEVERE", "MILD")
sample = data.frame(Ob=1:15000, SEVERITY=testPred)
write.csv(sample, "sample.csv", row.names = FALSE)
```

## Random Forrest

```{r}
set.seed(123)
library(randomForest)
rf.model = randomForest(as.factor(Severity) ~ 
                        road_closed+
                        duration+
                        isWeekend+
                        Distance.mi.+
                        slow+
                        DescriptionLen+
                        isHighRiskState+
                          hour+
                          month+
                          year+
                          County
                          ,
                        data = train.train.data)
summary(rf.model)
varImpPlot(rf.model)

train.test.pred = predict(rf.model, newdata = train.test.data,
                         type = "class")
table(train.test.pred, train.test.data$Severity)
tree.mis.rate=mean(train.test.pred!=train.test.data$Severity)
tree.mis.rate

```

```{r}
testPred = predict(rf.model, newdata = test,
                         type = "class")
# pred <- ifelse(testPred >= 0.5, "SEVERE", "MILD")
sample = data.frame(Ob=1:15000, SEVERITY=testPred)
write.csv(sample, "sample.csv", row.names = FALSE)
```


## GLM Model

```{r}
glm.model <- glm(as.factor(Severity) ~ 
                        road_closed+
                        duration+
                        isWeekend+
                        caution+
                        Distance.mi.+
                        slow+
                        DescriptionLen+
                        isHighRiskState+
                        interstate+
                          Junction+
                          hour+
                          month,
                 family = binomial(), data = train.train.data)

summary(glm.model)

glm.predict <- predict(glm.model, train.test.data,
                       type="response")
predTrain <- ifelse(glm.predict >= 0.35, "SEVERE", "MILD")
table(train.test.data$Severity, predTrain)
mean(train.test.data$Severity != predTrain)


# pred <- ifelse(testPred >= 0.5, "SEVERE", "MILD")
# sample = data.frame(Ob=1:15000, SEVERITY=pred)
# write.csv(sample, "sample.csv", row.names = FALSE)

# train.test.pred = predict(glm.model, newdata = train.test.data,type = "class")
# table(train.test.pred, train.test.data$Severity)
# tree.mis.rate=mean(train.test.pred!=train.test.data$Severity)
# tree.mis.rate
```


## XGBoost model

```{r}
library(caret)
library(xgboost)

set.seed(123)
xgb_default <- train(as.factor(Severity) ~ 
                        road_closed+
                        duration+
                        isWeekend+
                        isRushHour+
                        caution+
                        Distance.mi.+
                        slow+
                        DescriptionLen+
                        isHighRiskState+
                        interstate,
                   data = train.train.data, 
                   method = "xgbTree")

library(tidyverse)
pred_xgb <- xgb_default %>% predict(train.test.data)
# Compute model prediction accuracy rate
mean(pred_xgb != train.test.data$Severity)

# pred = xgb_default %>% predict(test)
# sample = data.frame(Ob=1:15000, SEVERITY=pred)
# write.csv(sample, "sample.csv", row.names = FALSE)
```



